FROM node:8.9.1-alpine

RUN mkdir -p /usr/src/app/server

WORKDIR /usr/src/app
ADD ./server ./server

RUN cd server && \
    npm install && \
    npm prune --production

WORKDIR /usr/src/app/server

CMD [ "npm", "start" ]

EXPOSE 3000